language: cpp
os: linux
dist: xenial
addons:
  apt:
    packages:
      - g++-multilib
before_install:
  - tar zxf vendors/centos6-sysroot.tar.gz -C /tmp/
script:
  - mkdir buildx64 && pushd buildx64 && (source /tmp/centos6-sysroot/setx64.sh && cmake ..) && make VERBOSE=1 && make test && ldd base/tests && popd
  - mkdir buildx86 && pushd buildx86 && (source /tmp/centos6-sysroot/setx86.sh && cmake ..) && make VERBOSE=1 && make test && ldd base/tests && popd
