language: cpp
os: linux
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-multilib
before_install:
  - tar zxf vendors/centos6-sysroot.tar.gz -C /tmp/
  - source /tmp/centos6-sysroot/setx64.sh
script:
  - mkdir build && pushd build
  - cmake ../base
  - make VERBOSE=1 && make test
  - ldd tests
